name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  paths:
#    - '*/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

#    - name: purge-cache
#      uses: MyAlbum/purge-cache@v1
#      with:
#        token: '${{ secrets.GITHUB_TOKEN }}'
#        debug: true

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'corretto'

    - name: Build nordnet-dev-authenticator
#      working-directory: .
      run: ./gradlew clean build bootJar

    - name: Upload dev-authenticator.jar to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/libs/dev-authenticator.jar
        asset_name: dev-authenticator.jar
        tag: ${{ github.ref }}
        overwrite: true
        body: "Nordnet Dev Authenticator"
