name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#  paths:
#    - '*/**'

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

#    - name: purge-cache
#      uses: MyAlbum/purge-cache@v1
#      with:
#        token: '${{ secrets.GITHUB_TOKEN }}'
#        debug: true

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'corretto'

    - name: Build nordnet-dev-authenticator
#      working-directory: .
      run: ./gradlew clean build

    - name: Publish package
      run: ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
